baseurl = "https://alexdunn.io/"
title = ""
author = "Alex Dunn"
canonifyurls = true
languagecode = "en"
theme = "black_and_white"
publishDir = "../"

pygmentsstyle       = "colorful"
pygmentscodefences  = true

[params]
  sitename = "alexdunn.io"
  disableWebFonts = false


[[menu.main]]
    name = "Work"
    url  = "/work/"
[[menu.main]]
    name = "Posts"
    url  = "/posts/"
[[menu.main]]
    name = "Random"
    url  = "/random/"
