baseurl = "https://ardunn.us/"
title = ""
author = "Alex Dunn"
canonifyurls = true
languagecode = "en"
theme = "black_and_white"
publishDir = "../"

pygmentsstyle       = "colorful"
pygmentscodefences  = true

[params]
  sitename = "ardunn.us"
  disableWebFonts = false


[[menu.main]]
    name = "CV"
    url  = "/cv/"
[[menu.main]]
    name = "Posts"
    url  = "/posts/"
[[menu.main]]
    name = "Projects"
    url  = "/projects/"
