baseurl = "https://alexdunn.io/"
title = "Alex Dunn personal site"
author = "David Hamp-Gonsalves"
canonifyurls = true
languagecode = "en"
theme = "black_and_white"
publishDir = "../"


pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "alexdunn.io"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "/about/"
[[menu.main]]
    name = "Resume/CV"
    url  = "/post/"
[[menu.main]]
    name = "Posts"
    url  = "/post/"
[[menu.main]]
    name = "Fun"
    url  = "/fun/"
