baseurl = "https://alexdunn.io/"
title = ""
author = "Alex Dunn"
canonifyurls = true
languagecode = "en"
theme = "black_and_white"
publishDir = "../"


pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "alexdunn.io"
  disableWebFonts = false


[[menu.main]]
    name = "CV"
    url  = "/cv/"
[[menu.main]]
    name = "Posts"
    url  = "/posts/"
[[menu.main]]
    name = "Fun"
    url  = "/fun/"
